Infscp01 124 feature update client
ahmetDev7/projecthr pull request #116
Opened 2024-12-03 16:58 UTC by Sidim9

# Issue
https://project-hr.atlassian.net/browse/INFSCP01-124

## Description
Je kan nu een Client updaten met behulp van /clients/clientid

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

Steps to test
Outline the steps to test or reproduce the PR here.

1. Run de /cleints in de .rest bestand

Related PRs
n.v.t.

2024-12-09 16:12 UTC, AlperenBaytimur commented on api/Controllers/ClientsController.cs
> +                ZipCode = foundClient.Address?.ZipCode,
je hebt vergeten om ook HouseNumberExtensionExtra toe te voegen onder HouseNumberExtension

2024-12-09 16:21 UTC, AlperenBaytimur commented on api/REST/Clients/Clients.rest
> +PUT http://localhost:5000/api/clients/fa5946ab-2ab8-4274-a2eb-b717855f8dca
je update functie werkt, maar het zou iets beter zijn als je ook .restfile tests hebt voor verschillende situaties met de update functie

2024-12-09 16:23 UTC, AlperenBaytimur requested changes
Je bent er bijna, nog deze kleine dingetjes en je bent er !

2024-12-10 12:20 UTC, Sidim9 commented on api/REST/Clients/Clients.rest
> +PUT http://localhost:5000/api/clients/fa5946ab-2ab8-4274-a2eb-b717855f8dca
Ik test alleen de goeie endpoints

2024-12-11 08:18 UTC, AlperenBaytimur approved these changes
ziet er goed uit

2024-12-11 08:19 UTC, merged