Infscp01 123 feature delete client
ahmetDev7/projecthr pull request #140
Opened 2024-12-12 15:35 UTC by Sidim9

# Issue
https://project-hr.atlassian.net/browse/INFSCP01-123

## Description
Rebase van client delete function

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## Steps to Test 
Outline the steps to test or reproduce the PR here.

1. Run de Delete methode in de .REST file /clients
## Related PRs
List related PRs against other branches and projects:

branch | PR
n.v.t.

2024-12-17 11:25 UTC, ahmetDev7 approved these changes

2024-12-18 15:09 UTC, Sharif-C requested changes

2024-12-18 15:09 UTC, Sharif-C commented on api/providers/ClientsProvider.cs
> +
checken als een client gekoppeld is aan iets voor dat je verwijderd bijvoorbeeld shipments

2024-12-19 12:52 UTC, Sharif-C requested changes

2024-12-19 12:52 UTC, Sharif-C commented on api/providers/ClientsProvider.cs
> +        if (_db.Orders.Any(o => o.BillToClientId == id))
ship to client moet je ook checken

2024-12-19 13:10 UTC, merged