Infscp01 182 fix put locations
ahmetDev7/projecthr pull request #58
Opened 2024-11-23 12:22 UTC by Sidim9

# Issue
https://project-hr.atlassian.net/browse/INFSCP01-182

## Description
De Put had een PATCH functionaliteit maar nu werkt het als een PUT

## Type of change
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## Steps too test
je kan de rest file gebruiken

## Related PRs
n.v.t.
branch | PR
n.v.t.

2024-11-23 13:59 UTC, AlperenBaytimur commented on api/.env.development
je compared via main, je moet dat development maken

2024-11-23 14:00 UTC, AlperenBaytimur requested changes
verander je compare van main naar development

2024-11-23 14:40 UTC, Sharif-C requested changes
bool hasChanges = false;

Je moet deze nog weghalen

2024-11-26 09:44 UTC, Sharif-C approved these changes

2024-11-26 09:48 UTC, AlperenBaytimur approved these changes
goed genoeg

2024-11-26 09:48 UTC, merged